// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5IC66d09V-vploJwxDLm0pyXrx3Y8Vw',
    appId: '1:687793479749:android:406552a4d10830d402432c',
    messagingSenderId: '687793479749',
    projectId: 'fir-auth-cb388',
    storageBucket: 'fir-auth-cb388.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcWBBuVImLsszva-8QfaNcdYszp7yk8_c',
    appId: '1:687793479749:web:20357f3ae7178f9a02432c',
    messagingSenderId: '687793479749',
    projectId: 'fir-auth-cb388',
    authDomain: 'fir-auth-cb388.firebaseapp.com',
    storageBucket: 'fir-auth-cb388.appspot.com',
    measurementId: 'G-2BZ1G2P1TC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1U3hrVaA7yM_YNHhicLEqMHNsi2EGz8I',
    appId: '1:687793479749:ios:6dbf87460f62351202432c',
    messagingSenderId: '687793479749',
    projectId: 'fir-auth-cb388',
    storageBucket: 'fir-auth-cb388.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1U3hrVaA7yM_YNHhicLEqMHNsi2EGz8I',
    appId: '1:687793479749:ios:6dbf87460f62351202432c',
    messagingSenderId: '687793479749',
    projectId: 'fir-auth-cb388',
    storageBucket: 'fir-auth-cb388.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcWBBuVImLsszva-8QfaNcdYszp7yk8_c',
    appId: '1:687793479749:web:d318d3932cdcfa8502432c',
    messagingSenderId: '687793479749',
    projectId: 'fir-auth-cb388',
    authDomain: 'fir-auth-cb388.firebaseapp.com',
    storageBucket: 'fir-auth-cb388.appspot.com',
    measurementId: 'G-HT84VME9GM',
  );

}